// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRERsM9_TC_Ffx4CDWHUl7kYXkndHcEiE',
    appId: '1:272216470454:web:4927f61337a6f84e290717',
    messagingSenderId: '272216470454',
    projectId: 'g1-easy-hire',
    authDomain: 'g1-easy-hire.firebaseapp.com',
    storageBucket: 'g1-easy-hire.firebasestorage.app',
    measurementId: 'G-C9LC81VEP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwbOe8bPM72sOIdVDOY5lFcbZV3tSz6WU',
    appId: '1:272216470454:android:ceed28bf9c285a2e290717',
    messagingSenderId: '272216470454',
    projectId: 'g1-easy-hire',
    storageBucket: 'g1-easy-hire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_2lezLVaHX1PRJrbQszSUr3uKWTCUYg',
    appId: '1:272216470454:ios:34ca7e07f7690924290717',
    messagingSenderId: '272216470454',
    projectId: 'g1-easy-hire',
    storageBucket: 'g1-easy-hire.firebasestorage.app',
    iosClientId: '272216470454-aa01susfhagho1nkpkn608pa05ond7vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyHire',
  );
}
